version: 0.2

phases:
  build:
    commands:
      - echo "Checking files"
      - pwd
      - ls -la
      - find . -maxdepth 3 -name pom.xml
      - echo "Starting maven build"
      - mvn -B package --file pom.xml
