version: 0.2

phases:

  install:
    commands:
      - echo Installing dependencies
      - mvn -version

  build:
    commands:
      - echo Starting Maven build
      - mvn clean test -B

reports:
  test-report:
    files:
      - '**/surefire-reports/*.xml'
    file-format: JUNIT
