
name: Selenium Cross Browser CI

on:
  push:
  pull_request:

jobs:

  test:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Setup Firefox
        uses: browser-actions/setup-firefox@v1

      - name: Run Tests
        run: mvn test
